# Generated by Django 4.2.4 on 2023-09-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheatingDetection', '0003_alter_submission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sub_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
