# Generated by Django 4.2.4 on 2023-10-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheatingDetection', '0005_remove_submission_path_submission_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sub_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
